Do not exit whole program on error
This gives user a chace to recover from failure. Errors now results in
message being printed to screen as well as proper return code being
passed to caller. This way 'use' function could be used the way that end
of available input might be catched by user script.

Solution must yet be found for situation where user is not interested in
return code, but rather want to close the program immediately (usually
the case).

diff --git a/scripts/hdcb-func.sh.in b/scripts/hdcb-func.sh.in
--- a/scripts/hdcb-func.sh.in
+++ b/scripts/hdcb-func.sh.in
@@ -86,8 +86,8 @@ function define {
 # NOTE: if shellvar ends with l, the value will be read as little-endian
 function use {
     if [ $# -lt 1 ]; then
-        echo "Error! Invalid arguments for use()";
-        exit 1;
+        echo "Error! Invalid arguments for use()" >&2;
+        return 1;
     fi;
     len=${vars[$1,1]};
     shellvar=""
@@ -105,15 +105,20 @@ function use {
         endianness=${shellvar:$typeindex:2};
         case "$endianness" in
             "_l" )
-                value_le $shellvar $cursor $len; ;;
+                value_le $shellvar $cursor $len || return 1;
+                ;;
             "_b" )
-                value_be $shellvar $cursor $len; ;;
+                value_be $shellvar $cursor $len || return 1;
+                ;;
             * )
                 echo "Suffix $endianness not supported"
-                eval $shellvar=0; ;;
+                eval $shellvar=0;
+                return 1;
+                ;;
         esac
     fi;
     color $len "${vars[$1,2]}:${vars[$1,3]}"
+    return 0;
 }
 
 function legend {
